---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items: "{{
    manala_mysql_install_packages|ternary(
      manala_mysql_install_packages,
      [
        'mysql-server',
        'mysql-client'
      ]
    )
  }}"
