---

# Install
- import_tasks: install.yml
  tags:
    - manala_mysql

# Configs
- import_tasks: configs.yml
  tags:
    - manala_mysql

# Services
- import_tasks: services.yml
  tags:
    - manala_mysql
    - manala_mysql.services
    - manala.services

# Users
- import_tasks: users.yml
  tags:
    - manala_mysql

# Databases
- import_tasks: databases.yml
  tags:
    - manala_mysql

# Replications
- import_tasks: replications.yml
  tags:
    - manala_mysql
